version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: